name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Version packages
        id: version
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Working directory is not clean. Aborting."
            exit 1
          fi

          pnpm changeset version

          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_exist=true" >> $GITHUB_ENV
          else
            echo "changes_exist=false" >> $GITHUB_ENV
          fi

      - name: Commit and push version changes
        if: env.changes_exist == 'true'
        run: |
          git add .
          git commit -m "chore: version packages [skip ci]"
          git push

      - name: Publish to npm
        if: env.changes_exist == 'true'
        run: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
